spring.application.name=Trace
# Server
server.port=8080
server.error.whitelabel.enabled=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

# View resolver for JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# DataSource (adjust to your environment)
spring.datasource.url=winpg-prod-postgres.cp2y480osv5a.ap-south-1.rds.amazonaws.com:5432/trace
spring.datasource.username=#CHANGE_ME
spring.datasource.password=#CHANGE_ME
spring.datasource.hikari.maximum-pool-size=20

# JPA (optional)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.jdbc.core=WARN
logging.level.com.sybyl.trace=INFO
logging.level.org.springframework.web=WARN
LOG_DIR=C:/trace_log
LOG_NAME=trace-app

# SMTP for emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=#CHANGE_ME
spring.mail.password=#CHANGE_ME
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

app.public-base-url=#CHANGE_ME

# File Upload Limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Windows Paths
app.upload.margin-reports.path=C:/trace_docs/margin-reports
app.upload.additional-expenses.path=C:/trace_docs/additional-expenses
app.upload.invoices.path=C:/trace_docs/invoices


# === DB BACKUP SCHEDULER ===
app.backup.enabled=true
# Run every day at 02:30
app.backup.cron=0 30 2 * * *
app.backup.recipient=#CHANGE_ME
app.backup.from=#CHANGE_ME
app.backup.temp-dir=C:/trace_backups

# Optional: full path to pg_dump if not in PATH
app.backup.pg-dump-path=C:/Program Files/PostgreSQL/17/bin/pg_dump.exe

# --- Notification Cleanup Job ---
app.notifications.cleanup.enabled=true
app.notifications.cleanup.days=90
app.notifications.cleanup.cron=0 15 2 * * *


