package com.sybyl.trace.notification;

public enum NotificationType {
	USER_ACTIVATED,
	
	ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_DELETED,

    MARGIN_CREATED,
    MARGIN_UPDATED,
    MARGIN_APPROVED_FINANCE,
    MARGIN_APPROVED_CEO,
    MARGIN_REJECTED,

    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_APPROVED_CEO,
    EXPENSE_APPROVED_CFO,
    EXPENSE_REJECTED,
    
    INVOICE_CREATED,
    INVOICE_UPDATED
}
